listaPokemon= {
    "Absol-Mega-Z": ["A-", 7, True, False, True, True, False, True, True, False, True, True, "https://pokepast.es/282270436d6b384d/raw"],
 "Altaria": ["B-", 4, True, False, True, False, True, True, False, False, True, True, "https://pokepast.es/67e7f8aea1e8d7c8/raw"],
 "Annihilape": ["C+", 3, True, False, True, True, True, True, False, False, True, True, "https://pokepast.es/1c732e2c02c138e7/raw"],
 "Arcanine-Hisui": ["B+", 6, True, False, True, True, True, True, True, False, True, False, "https://pokepast.es/cbeec3196c8b02ef/raw"],
 "Articuno": ["C+", 3, True, False, False, False, True, True, False, False, True, True, "https://pokepast.es/3f8227b9344e966f/raw"],
 "Astrolotl": ["C", 2, False, False, True, False, False, True, True, True, False, True, "https://pokepast.es/269ef2b8696bfc43/raw"],
 "Audino-Mega": ["A+", 9, True, True, False, False, False, False, False, False, True, True, "https://pokepast.es/5a7f37850639d449/raw"],
 "Caribolt": ["B+", 6, True, False, True, True, True, True, True, True, False, False, "https://pokepast.es/ff90cd234003e595/raw"],
 "Charizard-Mega-X": ["A-", 7, True, False, True, False, False, True, False, False, True, False, "https://pokepast.es/121980aae8d9aad6/raw"],
 "Chesnaught-Mega": ["A-", 7, True, False, True, True, True, True, False, True, False, True, "https://pokepast.es/fb185197db172621/raw"],
 "Chi-Yu": ["C-", 1, True, True, False, False, True, False, True, False, True, True, "https://pokepast.es/561eadffbfd2da40/raw"],
 "Chien-Pao": ["B", 5, True, True, False, True, True, True, True, False, True, True, "https://pokepast.es/d5573f81108e5be2/raw"],
 "Chimecho-Mega": ["B+", 6, True, True, False, False, False, True, False, False, True, True, "https://pokepast.es/96ae4a2f66b465e0/raw"],
 "Cinderace": ["B+", 6, True, False, True, False, False, True, True, True, False, True, "https://pokepast.es/77de79bfaa286c1b/raw"],
 "Clawitzer": ["D", 0, True, False, True, False, False, False, True, True, False, True, "https://pokepast.es/d8dcc19259d07e7f/raw"],
 "Comfey": ["C+", 3, True, True, False, True, False, False, True, False, True, True, "https://pokepast.es/1441036bc5a8b37d/raw"],
 "Crobat": ["C+", 3, True, False, True, False, True, False, False, False, True, True, "https://pokepast.es/e0432190ee763a1c/raw"],
 "Cryogonal": ["D", 0, True, True, False, False, True, True, False, False, True, False, "https://pokepast.es/3e7385adac5b6587/raw"],
 "Delphox-Mega": ["S", 10, True, True, False, True, True, True, True, True, False, True, "https://pokepast.es/25ae694dac13ad72/raw"],
 "Deoxys-Speed": ["B+", 6, False, True, True, False, False, True, True, False, True, True, "https://pokepast.es/3b2c98ae00f746ab/raw"],
 "Dondozo": ["C", 2, True, True, True, False, False, True, False, False, True, False, "https://pokepast.es/414b0353cb9ee3a6/raw"],
 "Dragalge-Mega": ["A", 8, True, True, False, False, True, True, False, True, False, False, "https://pokepast.es/81e350b167a45845/raw"],
 "Dragapult": ["B+", 6, True, False, True, True, True, True, True, True, False, True, "https://pokepast.es/04d4345bf38ca24a/raw"],
 "Drampa-Mega": ["A-", 7, True, True, False, False, True, True, True, False, True, False, "https://pokepast.es/982683ab85f52a5c/raw"],
 "Eelektross-Mega": ["C-", 1, True, True, False, False, False, True, False, False, True, False, "https://pokepast.es/e0d73e62b40dbab1/raw"],
 "Electrode": ["B", 5, False, True, False, False, False, False, True, False, True, True, "https://pokepast.es/37b4e0c7ecf12152/raw"],
 "Emboar-Mega": ["B+", 6, False, False, True, True, True, True, False, False, True, False, "https://pokepast.es/2d5650126d481549/raw"],
 "Eternatus-Eternamax": ["B+", 6, True, False, True, False, True, True, False, True, False, False, "https://pokepast.es/adcb7ef0c31c1ad6/raw"],
 "Excadrill": ["C", 2, True, False, True, True, True, False, True, False, True, True, "https://pokepast.es/76dca7643d69a9b3/raw"],
 "Falinks-Mega": ["C-", 1, True, False, True, False, False, True, True, True, False, True, "https://pokepast.es/adb92c46e3635e02/raw"],
 "Feraligatr-Mega": ["B+", 6, True, False, True, True, False, True, True, True, False, False, "https://pokepast.es/0adbd3ebe9693037/raw"],
 "Ferrothorn": ["B+", 6, True, False, True, False, True, False, False, False, True, False, "https://pokepast.es/04fa187f1d743009/raw"],
 "Floette-Mega": ["A", 8, True, True, False, False, False, True, False, True, False, False, "https://pokepast.es/cbeba1793bb98f4d/raw"],
 "Garbodor": ["C-", 1, False, False, True, False, False, True, False, False, True, False, "https://pokepast.es/f648719daf5baa8c/raw"],
 "Garganacl": ["A+", 9, True, True, True, False, True, True, False, False, True, False, "https://pokepast.es/7c82b7c005d24523/raw"],
 "Gengar": ["C+", 3, True, True, False, False, True, True, True, False, True, True, "https://pokepast.es/2e5ada207f3dfc77/raw"],
 "Gholdengo": ["C+", 3, True, True, False, True, True, True, True, False, True, True, "https://pokepast.es/3bd5057e40fe2df1/raw"],
 "Golisopod-Mega": ["A", 8, False, False, True, False, True, True, False, False, True, False, "https://pokepast.es/aca096c660cc1813/raw"],
 "Golurk-Mega": ["C", 2, False, False, True, False, True, True, True, False, True, False, "https://pokepast.es/61dcc316b4e372e6/raw"],
 "Goodra-Hisui": ["A+", 9, False, True, False, False, False, True, False, True, False, False, "https://pokepast.es/81cf513d6028556c/raw"],
 "Gourgeist-*": ["C", 2, True, False, True, True, True, True, True, True, False, True, "https://pokepast.es/d3f84941553549f9/raw"],
 "Greninja-*": ["B+", 6, True, False, True, False, True, True, True, True, False, True, "https://pokepast.es/058e80a1c59fb04a/raw"],
 "Gyarados": ["B+", 6, True, False, True, False, True, True, True, False, True, False, "https://pokepast.es/5d12e12b8736cbc3/raw"],
 "Hatterene": ["C", 2, False, True, False, False, False, True, True, True, False, True, "https://pokepast.es/147d50f81d8611ed/raw"],
 "Haxorus": ["B", 5, True, False, True, False, False, True, True, False, True, False, "https://pokepast.es/a64543335a42be39/raw"],
 "Inteleon": ["C-", 1, True, False, False, True, False, False, True, True, False, True, "https://pokepast.es/5e4e540e004e6f65/raw"],
 "Iron Treads": ["A", 8, True, False, True, False, True, True, True, False, True, False, "https://pokepast.es/21acae57a15648c8/raw"],
 "Kingambit": ["S", 10, True, False, True, False, True, True, True, False, True, False, "https://pokepast.es/06367fc118c80ecb/raw"],
 "Magneton": ["C", 2, False, True, False, False, True, True, False, False, True, True, "https://pokepast.es/a1766d4d495db889/raw"],
 "Manaphy": ["B+", 6, False, True, False, False, False, False, False, True, False, True, "https://pokepast.es/557f031026adb0aa/raw"],
 "Mareep": ["D", 0, True, False, True, False, False, True, False, True, False, True, "https://pokepast.es/2edd1d7540d8da06/raw"],
 "Marshadow": ["C+", 3, True, False, True, False, True, True, True, False, True, True, "https://pokepast.es/37374106bf5e7dae/raw"],
 "Meganium-Mega": ["B", 5, True, True, False, True, True, True, False, True, False, False, "https://pokepast.es/2b5f6554965dcc1d/raw"],
 "Meloetta": ["C-", 1, True, True, False, False, False, True, True, False, True, True, "https://pokepast.es/1f2451cb8e090923/raw"],
 "Meloetta-Pirouette": ["A-", 7, True, False, True, True, True, True, True, False, True, True, "https://pokepast.es/898ae46eafe7c5b8/raw"],
 "Moltres": ["A", 8, True, True, False, False, True, True, True, False, True, True, "https://pokepast.es/468e8cc5fa702f13/raw"],
 "Morpeko-Hangry": ["C", 2, False, False, True, True, True, True, True, True, False, True, "https://pokepast.es/ee12e177ab7140ed/raw"],
 "Ogerpon-Wellspring": ["A-", 7, True, False, True, True, False, False, True, False, True, True, "https://pokepast.es/548b7b122952d0ba/raw"],
 "Pecharunt": ["B", 5, False, True, True, False, True, True, False, False, True, True, "https://pokepast.es/8d6b82b5156cff72/raw"],
 "Pheromosa": ["A", 8, True, False, False, True, True, True, True, False, True, True, "https://pokepast.es/a6d7c6e30c3df37a/raw"],
 "Pikachu": ["D", 0, True, True, False, False, False, True, False, False, True, True, "https://pokepast.es/4d6f89f6ded62533/raw"],
 "Ramnarok": ["B+", 6, True, True, False, True, True, True, False, True, False, False, "https://pokepast.es/4db5688a3cf8571d/raw"],
 "Rapidash-Galar": ["C-", 1, True, False, True, True, False, False, True, False, True, True, "https://pokepast.es/1a824d625e131c4e/raw"],
 "Regieleki": ["S", 10, True, False, True, True, False, False, True, True, False, True, "https://pokepast.es/0782bc93227ae936/raw"],
 "Regigigas": ["C+", 3, True, False, True, False, False, True, False, True, False, False, "https://pokepast.es/633bfbd538598d86/raw"],
 "Roserade": ["B+", 6, True, True, False, False, True, True, False, True, False, True, "https://pokepast.es/0dc6a75dbde1e9d7/raw"],
 "Samurott-Hisui": ["B-", 4, True, False, True, True, True, True, True, False, True, True, "https://pokepast.es/db73bcb1d8388164/raw"],
 "Sceptile-Mega": ["A+", 9, True, True, False, True, True, True, False, False, True, True, "https://pokepast.es/6344b24b974c0ee2/raw"],
 "Scizor-Mega": ["A+", 9, True, False, True, False, True, True, False, True, False, False, "https://pokepast.es/c67ffbc08286a91d/raw"],
 "Scolipede-Mega": ["C+", 3, True, False, True, True, True, True, False, False, True, False, "https://pokepast.es/73db76dc0f6dc203/raw"],
 "Scovillain": ["B-", 4, False, False, False, False, False, True, False, False, True, True, "https://pokepast.es/b394941780fba382/raw"],
 "Scrafty-Mega": ["B+", 6, True, False, True, False, True, True, False, False, True, True, "https://pokepast.es/b140931611516ab3/raw"],
 "Scream Tail": ["C+", 3, False, True, True, False, False, True, False, False, True, True, "https://pokepast.es/27ac867ff78ef2aa/raw"],
 "Shelgon": ["D", 0, True, False, True, False, False, True, False, False, True, False, "https://pokepast.es/876aca87feec449f/raw"],
 "Shuckle": ["A", 8, False, False, True, False, False, False, False, True, False, True, "https://pokepast.es/29df92f9fa86051d/raw"],
 "Silvally-*": ["B-", 4, True, True, False, False, False, True, False, False, True, False, "https://pokepast.es/d374c166b746a3ef/raw"],
 "Sirfetch'd": ["A-", 7, True, False, True, False, False, True, True, True, False, True, "https://pokepast.es/474854f015274afe/raw"],
 "Slaking": ["B-", 4, True, True, True, False, False, True, False, False, True, False, "https://pokepast.es/430120df9686fd03/raw"],
 "Snaelstrom": ["C-", 1, True, True, False, False, False, True, False, True, False, False, "https://pokepast.es/844742cf2bc7568e/raw"],
 "Spheal": ["D", 0, True, True, True, False, True, True, True, False, True, True, "https://pokepast.es/d5a738cead84c1fd/raw"],
 "Spiritomb": ["C", 2, True, True, False, False, False, True, False, True, False, False, "https://pokepast.es/1b9daf0aeda9c837/raw"],
 "Tapu Koko": ["A+", 9, True, False, True, True, False, True, True, False, True, True, "https://pokepast.es/26ca17815ba03226/raw"],
 "Tauros": ["C-", 1, True, False, True, True, False, True, True, False, True, True, "https://pokepast.es/f8fc6bb27e392090/raw"],
 "Terapagos-Terastal": ["A+", 9, False, True, False, False, False, True, False, False, True, True, "https://pokepast.es/4282db3d5ec60ad6/raw"],
 "Ting-Lu": ["A+", 9, False, True, True, False, True, False, False, False, True, False, "https://pokepast.es/022310ec860abf57/raw"],
 "Tinkaton": ["A-", 7, True, False, True, False, False, True, False, False, True, False, "https://pokepast.es/32ffe663f6ac85aa/raw"],
 "Toedscruel": ["B", 5, False, False, True, False, True, True, False, False, True, True, "https://pokepast.es/e509c94f33069934/raw"],
 "Togekiss": ["B-", 4, True, True, False, True, True, True, True, True, False, True, "https://pokepast.es/4c2cfed36d1604f7/raw"],
 "Tyranitar": ["C-", 1, False, False, True, False, True, True, False, True, False, False, "https://pokepast.es/664c04ce17b309b9/raw"],
 "Umbreon": ["D", 0, True, True, True, False, False, True, False, True, False, True, "https://pokepast.es/9b50b427a3b7a8cd/raw"],
 "Ursaluna-Bloodmoon": ["B", 5, False, True, False, False, False, True, False, False, True, False, "https://pokepast.es/35ad12ffc33067a0/raw"],
 "Venusaur-Mega": ["A", 8, True, True, False, False, True, True, False, False, True, False, "https://pokepast.es/bbc5d130a17780fc/raw"],
 "Victini": ["B", 5, True, False, True, True, True, False, False, False, True, True, "https://pokepast.es/be84245c284ed620/raw"],
 "Victreebel-Mega": ["D", 0, True, False, True, False, True, True, False, False, True, False, "https://pokepast.es/37cbc0ac0e5ab1d0/raw"],
 "Zapdos": ["A+", 9, True, True, False, True, False, True, True, False, True, True, "https://pokepast.es/5bd6f1f48b7354b9/raw"]
 }


formatos=["Clean Field", "Dia Especial", "Dia Fisico", "Aggresive Mons",
          "Mucho Cuidado", "No Pivot", "No Recovery", "Gen Par", "Gen Impar", "Bajando de Peso"
]